### ISSUE TITLE
GGP's car-free route after JFK not preferred by router

### ISSUE THREAD

**Issue by hcourt** [bikehopper/graphhopper#33]
These are the tags on Overlook Drive, a portion of the car-free JFK route:
![image](https://user-images.githubusercontent.com/2773087/158889694-b12bf8e8-9e36-47d2-8651-34351be0d42c.png)

The router does see `bicycle=yes` and will route on it, but won't prefer it as a route through the park because BikeCommonFlagEncoder does not look for `motor_vehicle=no`. 

I think one or two things should be done here:
1. Tag this segment in OSM as `bicycle=designated`, which will trigger this:
```
if (way.hasTag("bicycle", "designated") || way.hasTag("bicycle", "official")) {
            if ("path".equals(highway))
                weightToPrioMap.put(100d, VERY_NICE.getValue());
            else
                weightToPrioMap.put(100d, PREFER.getValue());
        }
```
2. Modify the above code to include `|| motor_vehicle=no`.

(edit: I later discovered almost all the route through the park has the same issue)

**Comment by hcourt** [comment]
I just finished updating the tags in OSM.

**Comment by abhumbla** [comment]
i like adding `|| motor_vehicle=no`, that seems right

**Comment by abhumbla** [comment]
more generally, i think we should have the router work with broadly observed OSM practices in our area, rather than need to edit OSM to trigger code in the router. though obv we should do our civic duty and make OSM more accurate where we can, i think it's unsustainable to be in the business of editing OSM at a large scale

**Comment by abhumbla** [comment]
@graue adds "we could also prefer `motor_vehicle=destination` for slow streets"

**Comment by abhumbla** [comment]
@hcourt is this fixed?

**Comment by rsarathy** [comment]
Is this fixed? Bikehopper directions from Pittsburgh Pub in the Sunset to Market & Castro utilize the full length of JFK promenade.

FWIW not all of JFK promenade is coded as `motor_vehicle=no`, just some select edges. Most of the edges have `motor_vehicle=bus` because of the GGP shuttle and MUNI's 43.

**Comment by graue** [comment]
That should probably be corrected in OpenStreetMap to `motor_vehicle=no` with a more specific (thus overriding) `bus=yes`. There are very few uses of `motor_vehicle=bus` worldwide and it's not documented in the wiki.

https://wiki.openstreetmap.org/wiki/Key:bus

Anyway, yes I think this is fixed. BikeHopper uses Middle and Overlook now. [Example](https://bikehopper.org/route/-122.50931752197576,37.76300192455297/to/Castro%20District%2C%20San%20Francisco%2C%2094114@-122.434957,37.7608561)
